live_config_reload = true
working_directory = "None"

# Themes --
import = [ 
  #"~/.config/alacritty/night_owl.toml"#,
  "~/.config/alacritty/nordic.toml"#,
#  "~/.config/alacritty/keybinds.toml"
]

[window]
title = "Alacritty"
decorations = "none"
blur = true
#opacity = 0.9
opacity = 0.8
padding.x = 10
padding.y = 10

[window.dimensions]
columns = 160
lines = 80

[cursor.style]
#shape= "Beam"
#blinking = "Never"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
#glyph_offset = { x = 1, y = 0 }
#normal.family = "MesloLGS Nerd Font Mono"
normal.family = "FiraCode Nerd Font"
normal.style = "Regular"
size = 12.0

[font.bold]
#family = "MesloLGS Nerd Font Mono"
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
#family = "MesloLGS Nerd Font Mono"
family = "FiraCode Nerd Font"
style = "Italic"
